name: codebloom
description: "CodeBloom"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core UI / Utils
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0

  # PDF + Printing Support
  pdf: ^3.10.6
  printing: ^5.12.0

  # Animations
  lottie: ^3.3.2

  # Icons
  font_awesome_flutter: ^10.7.0

  # Notifications
  flutter_local_notifications: ^17.0.0

  # Firebase (Stable Matching Set)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  firebase_messaging: ^15.1.2

  # State Management
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/illustration/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900
